### ISSUE TITLE
AtlasPrivateEndpoint cdk giving error : required key [ApiKeys] not found

### ISSUE THREAD

**Issue by dahiyahimanshu** [mongodb/awscdk-resources-mongodbatlas#30]
```
import os

from aws_cdk import (
    Stack, aws_ec2 as ec2,
)

from bda_constructs.bda_constructs import vpc_lookup
from constructs import Construct

from awscdk_resources_mongodbatlas import (AdvancedRegionConfig, AdvancedReplicationSpec,
                                           Specs, AccessListDefinition, IpAccessListProps,
                                           ProjectProps, ClusterProps, AtlasBasic, PrivateEndpoint,
                                           AtlasBasicPrivateEndpoint, AtlasBasicProps, PrivateEndpointProps,
                                           ProjectApiKey)


class MongodbStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        org_id_var = self.node.try_get_context('org_id') or os.getenv('')
        region_var = self.node.try_get_context('region')
        profile_name_var = self.node.try_get_context('profile')
        ip_addr_var = self.node.try_get_context('ip_addr')
        ip_comment_var = self.node.try_get_context('ip_comment')
        vpc_id = self.node.try_get_context('vpc_id')
        subnets = self.node.try_get_context('subnets').split(",")

        region_configs_var = [
            AdvancedRegionConfig(analytics_specs=Specs(node_count=1, instance_size="M10", ebs_volume_type="STANDARD"),
                                 electable_specs=Specs(node_count=3, instance_size="M10", ebs_volume_type="STANDARD"),
                                 priority=7,
                                 region_name=region_var)]
        replication_specs_var = [AdvancedReplicationSpec(advanced_region_configs=region_configs_var, num_shards=1)]

        access_list_defs_var = [AccessListDefinition(ip_address=ip_addr_var, comment=ip_comment_var)]

        # atlas_basic_l3 = AtlasBasic(self, "AtlasBasic-py-l3",
        #                             cluster_props=ClusterProps(replication_specs=replication_specs_var),
        #                             project_props=ProjectProps(org_id=org_id_var),
        #                             ip_access_list_props=IpAccessListProps(access_list=access_list_defs_var),
        #                             profile=profile_name_var)

        atlas_basic_props = AtlasBasicProps(cluster_props=ClusterProps(replication_specs=replication_specs_var),
                                            project_props=ProjectProps(org_id=org_id_var),
                                            ip_access_list_props=IpAccessListProps(access_list=access_list_defs_var),
                                            profile=profile_name_var
                                            )

        private_endpoint_props = PrivateEndpointProps(private_endpoints=[PrivateEndpoint(
            vpc_id=vpc_id,
            subnet_ids=subnets
        )])

        instance = AtlasBasicPrivateEndpoint(self, "AtlasBasic-private-endpoint-py-l3",
                                             atlas_basic_props=atlas_basic_props,
                                             private_endpoint_props=private_endpoint_props,
                                             # profile=profile_name_var
                                             )

```

```

[100%] success: Published 3423c3404b6bf05515dd31cc027c045ff998d549b7b371f3db43415407d8b595:current_account-current_region
Mongodb2Stack: creating CloudFormation changeset...
[█████████████████████████████████▏························] (4/7)

4:25:40 PM | CREATE_FAILED        | MongoDB::Atlas::PrivateEndpoint     | AtlasBasic-private...ate-endpoint-py-l3
Properties validation failed for resource AtlasBasicprivateendpointpyl3privateendpointAtlasBasicprivateendpointpyl309D4273A with mes
sage:
#: required key [ApiKeys] not found
4:25:41 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack          | Mongodb2Stack
The following resource(s) failed to create: [AtlasBasicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3ipaccesslistatlasba
sicAtlasBasicprivateendpointpyl3D2A51065, AtlasBasicprivateendpointpyl3privateendpointAtlasBasicprivateendpointpyl309D4273A, AtlasBa
sicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3dbuseratlasbasicAtlasBasicprivateendpointpyl3B2671B84, AtlasBasicprivat
eendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3clusteratlasbasicAtlasBasicprivateendpointpyl39F42C400]. Rollback requested by u
ser.
4:25:41 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack          | Mongodb2Stack
The following resource(s) failed to create: [AtlasBasicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3ipaccesslistatlasba
sicAtlasBasicprivateendpointpyl3D2A51065, AtlasBasicprivateendpointpyl3privateendpointAtlasBasicprivateendpointpyl309D4273A, AtlasBa
sicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3dbuseratlasbasicAtlasBasicprivateendpointpyl3B2671B84, AtlasBasicprivat
eendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3clusteratlasbasicAtlasBasicprivateendpointpyl39F42C400]. Rollback requested by u
ser.
```

While the atlasbasic pick the api keys from profile

**Comment by andreaangiolillo** [comment]
Hi 👋 

Thank you for bringing this issue to our attention. 

I was able to replicate the issue. We will need to release a new version of `MongoDB::atlas::PrivateEndpoint` in the `eu-west-1` region. In the meantime, a temporary workaround is to run the stack in the `us-east-1` region as the latest version of `MongoDB::atlas::PrivateEndpoint` in `us-east-1` uses the `Profile`.
I will add an update as soon as we have released a new version of `MongoDB::atlas::PrivateEndpoint` in `eu-west-1`.

Thanks!

**Comment by dahiyahimanshu** [comment]
MongoDB::Atlas::PrivateEndpoint

if you can publish the latest version of the template in eu-west-1 please i can see us-east-1 has 1.6.0 while eu-west-1 has version 1.2.0

**Comment by dahiyahimanshu** [comment]
any ETA please?

**Comment by dahiyahimanshu** [comment]
```
7:11:51 PM | CREATE_IN_PROGRESS   | MongoDB::Atlas::PrivateEndpoint     | AtlasBasic-private...ate-endpoint-py-l3
[████████████████▌·········································] (2/7)

7:52:21 PM | CREATE_FAILED        | MongoDB::Atlas::PrivateEndpoint     | AtlasBasic-private...ate-endpoint-py-l3
7:52:21 PM | CREATE_FAILED        | MongoDB::Atlas::PrivateEndpoint     | AtlasBasicprivatee...dpointpyl309D4273A
Internal Failure


 ❌  Mongodb2Stack failed: Error: The stack named Mongodb2Stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Internal Failure
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:380:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack2 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:383:145458)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:383:128776
    at async run (/usr/local/lib/node_modules/aws-cdk/lib/index.js:383:126782)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named Mongodb2Stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Internal Failure
    at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/index.js:383:129083)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:383:147507)
    at async exec4 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:438:51799)

Stack Deployments Failed: Error: The stack named Mongodb2Stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Internal Failure
```

Still failing with  v1.3.0

**Comment by dahiyahimanshu** [comment]
```
Mongodb2Stack: creating CloudFormation changeset...
[████████████████▌·········································] (2/7)

8:05:50 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack          | Mongodb2Stack
8:05:58 PM | CREATE_IN_PROGRESS   | MongoDB::Atlas::PrivateEndpoint     | AtlasBasic-private...ate-endpoint-py-l3
8:05:59 PM | CREATE_FAILED        | MongoDB::Atlas::ProjectIpAccessList | AtlasBasic-private...ate-endpoint-py-l3
Properties validation failed for resource AtlasBasicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3ipaccesslistatlasbasic
AtlasBasicprivateendpointpyl3D2A51065 with message:
#: required key [AccessList] not found

```

also i donot like provide ip_access_list_props in the cluster. basically i want the mongo db should be accessible through private endpoint from our vpc. It also gives me error.

**Comment by andreaangiolillo** [comment]
Hi 👋 ,

> Still failing with v1.3.0

The error is now different though 🤔 . 
Could you share the output of `cdk synth` and the latest version of your CDK code? Thanks 

> also i donot want to provide ip_access_list_props in the cluster. basically we want the mongo db should be accessible through private endpoint from our vpc. It also gives me error.

Unfortunately, AtlasBasis requires you to provide the access list. Your only option is to use the L1 constructors instead.

**Comment by dahiyahimanshu** [comment]
```
{
 "Resources": {
  "AtlasBasicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3projectatlasbasicAtlasBasicprivateendpointpyl3A20A1681": {
   "Type": "MongoDB::Atlas::Project",
   "Properties": {
    "Name": "atlas-project-419999",
    "OrgId": "640dba22c5b1cc609ab132d0",
    "Profile": "mycom-default"
   },
   "Metadata": {
    "aws:cdk:path": "Mongodb2Stack/AtlasBasic-private-endpoint-py-l3/atlas-basic-AtlasBasic-private-endpoint-py-l3/project-atlas-basic-AtlasBasic-private-endpoint-py-l3"
   }
  },
  "AtlasBasicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3clusteratlasbasicAtlasBasicprivateendpointpyl39F42C400": {
   "Type": "MongoDB::Atlas::Cluster",
   "Properties": {
    "ClusterType": "REPLICASET",
    "Profile": "mycom-default",
    "ProjectId": {
     "Fn::GetAtt": [
      "AtlasBasicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3projectatlasbasicAtlasBasicprivateendpointpyl3A20A1681",
      "Id"
     ]
    },
    "Name": "atlas-cluster-6039946",
    "ReplicationSpecs": [
     {
      "NumShards": 1,
      "AdvancedRegionConfigs": [
       {
        "RegionName": "EU_WEST_1",
        "AnalyticsSpecs": {
         "EbsVolumeType": "STANDARD",
         "InstanceSize": "M10",
         "NodeCount": 1
        },
        "ElectableSpecs": {
         "EbsVolumeType": "STANDARD",
         "InstanceSize": "M10",
         "NodeCount": 3
        },
        "Priority": 7
       }
      ]
     }
    ]
   },
   "Metadata": {
    "aws:cdk:path": "Mongodb2Stack/AtlasBasic-private-endpoint-py-l3/atlas-basic-AtlasBasic-private-endpoint-py-l3/cluster-atlas-basic-AtlasBasic-private-endpoint-py-l3"
   }
  },
  "AtlasBasicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3dbuseratlasbasicAtlasBasicprivateendpointpyl3B2671B84": {
   "Type": "MongoDB::Atlas::DatabaseUser",
   "Properties": {
    "DatabaseName": "admin",
    "Password": "atlas-pwd",
    "ProjectId": {
     "Fn::GetAtt": [
      "AtlasBasicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3projectatlasbasicAtlasBasicprivateendpointpyl3A20A1681",
      "Id"
     ]
    },
    "Roles": [
     {
      "DatabaseName": "admin",
      "RoleName": "atlasAdmin"
     }
    ],
    "Username": "atlas-user",
    "Profile": "mycom-default"
   },
   "Metadata": {
    "aws:cdk:path": "Mongodb2Stack/AtlasBasic-private-endpoint-py-l3/atlas-basic-AtlasBasic-private-endpoint-py-l3/db-user-atlas-basic-AtlasBasic-private-endpoint-py-l3"
   }
  },
  "AtlasBasicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3ipaccesslistatlasbasicAtlasBasicprivateendpointpyl3D2A51065": {
   "Type": "MongoDB::Atlas::ProjectIpAccessList",
   "Properties": {
    "AccessList": [
     {
      "IPAddress": "103.65.30.238"
     }
    ],
    "ProjectId": {
     "Fn::GetAtt": [
      "AtlasBasicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3projectatlasbasicAtlasBasicprivateendpointpyl3A20A1681",
      "Id"
     ]
    },
    "Profile": "mycom-default"
   },
   "Metadata": {
    "aws:cdk:path": "Mongodb2Stack/AtlasBasic-private-endpoint-py-l3/atlas-basic-AtlasBasic-private-endpoint-py-l3/ip-access-list-atlas-basic-AtlasBasic-private-endpoint-py-l3"
   }
  },
  "AtlasBasicprivateendpointpyl3privateendpointAtlasBasicprivateendpointpyl309D4273A": {
   "Type": "MongoDB::Atlas::PrivateEndpoint",
   "Properties": {
    "GroupId": {
     "Fn::GetAtt": [
      "AtlasBasicprivateendpointpyl3atlasbasicAtlasBasicprivateendpointpyl3projectatlasbasicAtlasBasicprivateendpointpyl3A20A1681",
      "Id"
     ]
    },
    "Region": "us-east-1",
    "PrivateEndpoints": [
     {
      "VpcId": "vpc-06aebd37bfbe4c11f",
      "SubnetIds": [
       "subnet-0e6864b2039026d73",
       "subnet-0fd6dd978ff590f6a"
      ]
     }
    ]
   },
   "Metadata": {
    "aws:cdk:path": "Mongodb2Stack/AtlasBasic-private-endpoint-py-l3/private-endpoint-AtlasBasic-private-endpoint-py-l3"
   }
  },
  "CDKMetadata": {
   "Type": "AWS::CDK::Metadata",
   "Properties": {
    "Analytics": "v2:deflate64:H4sIAAAAAAAA/zPSMzfVM1RMLC/WTU7J1s3JTNKrDi5JTM7WcU7LC0otzi8tSk4FsZ3z81IySzLz82p1AipLMvLz9I31DA2ASDGrODNTt6g0ryQzN1UvCEIDANl+HvZXAAAA"
   },
   "Metadata": {
    "aws:cdk:path": "Mongodb2Stack/CDKMetadata/Default"
   },
   "Condition": "CDKMetadataAvailable"
  }
 },
 "Conditions": {
  "CDKMetadataAvailable": {
   "Fn::Or": [
    {
     "Fn::Or": [
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "af-south-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "ap-east-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "ap-northeast-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "ap-northeast-2"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "ap-south-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "ap-southeast-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "ap-southeast-2"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "ca-central-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "cn-north-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "cn-northwest-1"
       ]
      }
     ]
    },
    {
     "Fn::Or": [
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "eu-central-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "eu-north-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "eu-south-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "eu-west-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "eu-west-2"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "eu-west-3"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "me-south-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "sa-east-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "us-east-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "us-east-2"
       ]
      }
     ]
    },
    {
     "Fn::Or": [
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "us-west-1"
       ]
      },
      {
       "Fn::Equals": [
        {
         "Ref": "AWS::Region"
        },
        "us-west-2"
       ]
      }
     ]
    }
   ]
  }
 },
 "Parameters": {
  "BootstrapVersion": {
   "Type": "AWS::SSM::Parameter::Value<String>",
   "Default": "/cdk-bootstrap/hnb659fds/version",
   "Description": "Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]"
  }
 },
 "Rules": {
  "CheckBootstrapVersion": {
   "Assertions": [
    {
     "Assert": {
      "Fn::Not": [
       {
        "Fn::Contains": [
         [
          "1",
          "2",
          "3",
          "4",
          "5"
         ],
         {
          "Ref": "BootstrapVersion"
         }
        ]
       }
      ]
     },
     "AssertDescription": "CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI."
    }
   ]
  }
 }
}
```
```

import os

from aws_cdk import (
    Stack, aws_ec2 as ec2,
)

from bda_constructs.bda_constructs import vpc_lookup
from constructs import Construct

from awscdk_resources_mongodbatlas import (AdvancedRegionConfig, AdvancedReplicationSpec,
                                           Specs, AccessListDefinition, IpAccessListProps,
                                           ProjectProps, ClusterProps, AtlasBasic, PrivateEndpoint,
                                           AtlasBasicPrivateEndpoint, AtlasBasicProps, PrivateEndpointProps,
                                           ProjectApiKey)


class MongodbStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        org_id_var = self.node.try_get_context('org_id') or os.getenv('')
        region_var = self.node.try_get_context('region')
        profile_name_var = self.node.try_get_context('profile')
        ip_addr_var = self.node.try_get_context('ip_addr')
        ip_comment_var = self.node.try_get_context('ip_comment')
        vpc_id = self.node.try_get_context('vpc_id')
        subnets = self.node.try_get_context('subnets').split(",")

        region_configs_var = [
            AdvancedRegionConfig(analytics_specs=Specs(node_count=1, instance_size="M10", ebs_volume_type="STANDARD"),
                                 electable_specs=Specs(node_count=3, instance_size="M10", ebs_volume_type="STANDARD"),
                                 priority=7,
                                 region_name=region_var)]
        replication_specs_var = [AdvancedReplicationSpec(advanced_region_configs=region_configs_var, num_shards=1)]

        access_list_defs_var = [AccessListDefinition(ip_address=ip_addr_var, comment=ip_comment_var)]

        # atlas_basic_l3 = AtlasBasic(self, "AtlasBasic-py-l3",
        #                             cluster_props=ClusterProps(replication_specs=replication_specs_var),
        #                             project_props=ProjectProps(org_id=org_id_var),
        #                             ip_access_list_props=IpAccessListProps(access_list=access_list_defs_var),
        #                             profile=profile_name_var)

        atlas_basic_props = AtlasBasicProps(cluster_props=ClusterProps(replication_specs=replication_specs_var),
                                            project_props=ProjectProps(org_id=org_id_var),
                                            ip_access_list_props=IpAccessListProps(access_list=access_list_defs_var),
                                            profile=profile_name_var
                                            )

        private_endpoint_props = PrivateEndpointProps(private_endpoints=[PrivateEndpoint(
            vpc_id=vpc_id,
            subnet_ids=subnets
        )])

        instance = AtlasBasicPrivateEndpoint(self, "AtlasBasic-private-endpoint-py-l3",
                                             atlas_basic_props=atlas_basic_props,
                                             private_endpoint_props=private_endpoint_props,
                                             # profile=profile_name_var
                                             )
        print(instance.atlas_basic.m_cluster.props)
```

**Comment by maastha** [comment]
Hi

The issue could be related to a mismatch in regions I see in the CDK synth. The cluster configuration is in EU_WEST_1 whereas "MongoDB::Atlas::PrivateEndpoint resource is for us-east-1. Since I don't see in region specified in the AtlasBasicPrivateEndpoint CDK construct specifically, it will default to your default AWS region. Please try setting default AWS region to eu-west-1 and setting the region in  AtlasBasicPrivateEndpoint construct as below:

```
instance = AtlasBasicPrivateEndpoint(self, "AtlasBasic-private-endpoint-py-l3",
                                             atlas_basic_props=atlas_basic_props,
                                             private_endpoint_props=private_endpoint_props,
                                             region="EU_WEST_1")
```

**Comment by dahiyahimanshu** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/5242576/233848207-2fa83f5f-8362-48c6-b765-85b37a3f5733.png">

i restested but the arn specified is in eu-west-1in my view.

**Comment by dahiyahimanshu** [comment]
after your proposed changes. i am getting below error
```


4:56:19 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack          | MongodbStack6
[████████▎·················································] (1/7)

4:59:13 PM | CREATE_FAILED        | MongoDB::Atlas::PrivateEndpoint     | AtlasBasic-private...ate-endpoint-py-l6
[████████████████▌·········································] (2/7)

4:59:13 PM | CREATE_FAILED        | MongoDB::Atlas::PrivateEndpoint     | AtlasBasic-private...ate-endpoint-py-l6
Resource handler returned message: "Error creating vcp Endpoint: MissingEndpoint: 'Endpoint' configuration is required for this serv
ice" (RequestToken: b8cd9aa8-d704-57c9-8c57-11652a151901, HandlerErrorCode: GeneralServiceException)
4:59:14 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack          | MongodbStack6
The following resource(s) failed to create: [AtlasBasicprivateendpointpyl6atlasbasicAtlasBasicprivateendpointpyl6clusteratlasbasicAt
lasBasicprivateendpointpyl66AAD87C0, AtlasBasicprivateendpointpyl6privateendpointAtlasBasicprivateendpointpyl6F8FA7D0C]. Rollback re
quested by user.
4:59:14 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack          | MongodbStack6
The following resource(s) failed to create: [AtlasBasicprivateendpointpyl6atlasbasicAtlasBasicprivateendpointpyl6clusteratlasbasicAt
lasBasicprivateendpointpyl66AAD87C0, AtlasBasicprivateendpointpyl6privateendpointAtlasBasicprivateendpointpyl6F8FA7D0C]. Rollback re
quested by user.
4:59:23 PM | DELETE_IN_PROGRESS   | MongoDB::Atlas::Cluster             | AtlasBasic-private...ate-endpoint-py-l6


```

**Comment by dahiyahimanshu** [comment]
worked for me now. thanks i had to provide instead "eu-west-1" in your proposed solution

`region="eu-west-1"`

**Comment by maastha** [comment]
Okay great, thanks for letting us know.
I will go ahead and close this issue in that case.
